[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "TethysDashDocs"
authors = [{name = "Corey Krewson", email = "ckrewson@aquaveo.com"}]
dynamic = ["version", "description"]
